import { Component, NgModule } from '@angular/core'
import {
  NbThemeModule,
  NbLayoutModule,
  NbIconModule,
  NbCardModule,
  NbButtonModule,
  NbSpinnerModule,
  NbSidebarModule,
  NbUserModule,
  NbActionsModule,
  NbContextMenuModule,
  NbMenuModule,
  NbToggleModule,
  NbListModule,
  NbAccordionModule,
  NbSelectModule,
  NbTabsetModule,
  NbInputModule,
  NbTooltipModule,
  NbCheckboxModule,
  NbPopoverModule,
  NbStepperModule,
  NbWindowModule,
} from '@nebular/theme'
import { NbEvaIconsModule } from '@nebular/eva-icons'
import { CommonModule } from '@angular/common'
import { FormsModule, ReactiveFormsModule } from '@angular/forms'

@NgModule({
  imports: [
    CommonModule,
    NbThemeModule.forRoot({ name: 'ccarbn' }),
    NbSidebarModule.forRoot(),
    NbMenuModule.forRoot(),
    NbLayoutModule,
    NbIconModule,
    NbEvaIconsModule,

    FormsModule,
    ReactiveFormsModule,

    NbAccordionModule,
    NbActionsModule,
    NbButtonModule,
    NbCardModule,
    NbCheckboxModule,
    NbContextMenuModule,
    NbInputModule,
    NbListModule,
    NbPopoverModule,
    NbSelectModule,
    NbSpinnerModule,
    NbStepperModule,
    NbTabsetModule,
    NbToggleModule,
    NbTooltipModule,
    NbUserModule,
    NbWindowModule.forRoot(),
  ],
  exports: [
    CommonModule,
    NbThemeModule,
    NbSidebarModule,
    NbMenuModule,
    NbLayoutModule,
    NbIconModule,
    NbEvaIconsModule,

    FormsModule,
    ReactiveFormsModule,

    NbAccordionModule,
    NbActionsModule,
    NbButtonModule,
    NbCardModule,
    NbCheckboxModule,
    NbContextMenuModule,
    NbInputModule,
    NbListModule,
    NbPopoverModule,
    NbSelectModule,
    NbSpinnerModule,
    NbStepperModule,
    NbTabsetModule,
    NbToggleModule,
    NbTooltipModule,
    NbUserModule,
    NbWindowModule,
  ],
})
export class SharedNebularModule {}
